version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    expose:
      - "8080"
  gui:
    build: ./wpe
    depends_on:
      - proxy
      - frontend
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/fb1:/dev/fb1"
      - "/dev/vchiq:/dev/vchiq"
